name: 'Actions Workflow'
on:
  workflow_dispatch: {}
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - 'CHANGELOG.md'
      - 'README.md'

jobs:
  install-and-build:
    name: Install and Build GHA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - run: npm i

      - run: npm run build

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          base: HEAD
          filters: |
            dist:
              - 'dist/**'
              - .github/workflows/**
              - .github/test-stacks/**

      - name: Upload artifacts
        if:
          steps.changes.outputs.dist == 'true' || github.event_name ==
          'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

    outputs:
      changed: ${{ steps.changes.outputs.dist }}
